package toolsmd

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"tars/internal/catalog"
	"tars/internal/paths"
	"tars/internal/tap"
)

const preamble = `# Tars connected tools

This file is generated by [tars](https://github.com/tars) — tools installed with ` + "`tars install`" + ` and refreshed with ` + "`tars connect`" + `.

**For coding agents (Cursor, Claude Code, Codex, etc.):** When the user asks about CLI tools, scripts, or integrations managed through tars, read this file (or the path the user @-mentions) and prefer these binaries and usage notes. Add ` + "`~/.tars/bin`" + ` to PATH in terminals where relevant.

---

`

// Refresh writes ~/.tars/tools.md from the catalog index, enriching missing usage from formulas when possible.
func Refresh() (string, error) {
	outPath, err := paths.ToolsMarkdown()
	if err != nil {
		return "", err
	}
	idx, err := catalog.ReadIndex()
	if err != nil {
		return "", err
	}
	body, err := render(idx)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return "", err
	}
	tmp := outPath + ".tmp"
	if err := os.WriteFile(tmp, []byte(body), 0o644); err != nil {
		return "", err
	}
	if err := os.Rename(tmp, outPath); err != nil {
		return "", err
	}
	return outPath, nil
}

func render(idx catalog.Index) (string, error) {
	tools := append([]catalog.ToolRecord(nil), idx.Tools...)
	sort.Slice(tools, func(i, j int) bool {
		return strings.ToLower(tools[i].Name) < strings.ToLower(tools[j].Name)
	})
	var b strings.Builder
	b.WriteString(preamble)
	if len(tools) == 0 {
		b.WriteString("*No tools installed yet.* Run `tars install <formula>` then `tars connect`.\n")
		return b.String(), nil
	}
	for _, t := range tools {
		if err := writeToolSection(&b, t); err != nil {
			return "", err
		}
	}
	return b.String(), nil
}

func writeToolSection(b *strings.Builder, rec catalog.ToolRecord) error {
	title := rec.Name
	if title == "" {
		title = "(unknown)"
	}
	fmt.Fprintf(b, "## %s\n\n", title)
	fmt.Fprintf(b, "- **Version:** %s\n", rec.Version)
	if rec.Tap != "" {
		fmt.Fprintf(b, "- **Tap:** %s\n", rec.Tap)
	}
	if rec.InstallPath != "" {
		fmt.Fprintf(b, "- **Install path:** `%s`\n", rec.InstallPath)
	}
	b.WriteString("\n")
	text := resolveUsageText(rec)
	for _, para := range strings.Split(text, "\n\n") {
		p := strings.TrimSpace(para)
		if p == "" {
			continue
		}
		b.WriteString(p)
		b.WriteString("\n\n")
	}
	b.WriteString("---\n\n")
	return nil
}

func resolveUsageText(rec catalog.ToolRecord) string {
	u := strings.TrimSpace(rec.Usage)
	if u != "" {
		return u
	}
	if f, _, err := tap.FindFormula(rec.Name); err == nil {
		return f.AgentUsageText()
	}
	if d := strings.TrimSpace(rec.Description); d != "" {
		return d
	}
	if rec.Model != nil {
		if s := strings.TrimSpace(rec.Model.Summary); s != "" {
			return s
		}
	}
	return "*(No usage text in the formula. Add a `usage` field, or `description` and optional `model.summary`, to the tool’s JSON formula.)*"
}
